"""add error_records table (86bc997wr)

The ErrorRecord model was coded long ago but never migrated; this makes it a
real table so run failures can be queried across runs.

Revision ID: 3babe9e8ec00
Revises: fb966212df72
Create Date: 2026-09-29 08:51:27.425528

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3babe9e8ec00"
down_revision: Union[str, None] = "fb966212df72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "error_records",
        sa.Column("error_id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("component", sa.String(length=50), nullable=False),
        sa.Column("error_type", sa.String(length=50), nullable=False),
        sa.Column("dedup_subtype", sa.String(length=100), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("agent_name", sa.String(length=30), nullable=True),
        sa.Column("stock_ticker", sa.String(length=20), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("stack_trace", sa.Text(), nullable=True),
        sa.Column("context_json", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("auto_fix_proposed", sa.Text(), nullable=True),
        sa.Column("auto_fix_status", sa.String(length=20), nullable=True),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("first_seen", sa.DateTime(), nullable=False),
        sa.Column("last_seen", sa.DateTime(), nullable=False),
        sa.Column("related_error_ids", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("error_id"),
    )
    op.create_index(
        op.f("ix_error_records_component"), "error_records", ["component"], unique=False
    )
    op.create_index(
        op.f("ix_error_records_error_type"), "error_records", ["error_type"], unique=False
    )
    op.create_index(op.f("ix_error_records_run_id"), "error_records", ["run_id"], unique=False)
    op.create_index(op.f("ix_error_records_severity"), "error_records", ["severity"], unique=False)
    op.create_index(op.f("ix_error_records_status"), "error_records", ["status"], unique=False)
    op.create_index(
        op.f("ix_error_records_timestamp"), "error_records", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_error_records_timestamp"), table_name="error_records")
    op.drop_index(op.f("ix_error_records_status"), table_name="error_records")
    op.drop_index(op.f("ix_error_records_severity"), table_name="error_records")
    op.drop_index(op.f("ix_error_records_run_id"), table_name="error_records")
    op.drop_index(op.f("ix_error_records_error_type"), table_name="error_records")
    op.drop_index(op.f("ix_error_records_component"), table_name="error_records")
    op.drop_table("error_records")
    # ### end Alembic commands ###
