"""add run_quality_summary table

Revision ID: 416d5dbac42d
Revises: 5ef880ea002b
Create Date: 2026-09-24 19:18:13.962235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '416d5dbac42d'
down_revision: Union[str, None] = '5ef880ea002b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_quality_summary',
    sa.Column('summary_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('wall_clock_ms', sa.Integer(), nullable=False),
    sa.Column('total_llm_ms', sa.Integer(), nullable=False),
    sa.Column('slowest_call_ms', sa.Integer(), nullable=True),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('retry_calls', sa.Integer(), nullable=False),
    sa.Column('total_prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('total_completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_thinking_chars', sa.Integer(), nullable=False),
    sa.Column('truncated_calls', sa.Integer(), nullable=False),
    sa.Column('empty_content_calls', sa.Integer(), nullable=False),
    sa.Column('validator_failures', sa.Integer(), nullable=False),
    sa.Column('gate1_passed', sa.Boolean(), nullable=True),
    sa.Column('gate1_reason', sa.String(length=255), nullable=True),
    sa.Column('gate2_passed', sa.Boolean(), nullable=True),
    sa.Column('gate2_reason', sa.String(length=255), nullable=True),
    sa.Column('stock_outlook', sa.String(length=20), nullable=True),
    sa.Column('overall_confidence', sa.Integer(), nullable=True),
    sa.Column('agents_with_empty_key_factors', sa.JSON(), nullable=True),
    sa.Column('agents_with_empty_risks', sa.JSON(), nullable=True),
    sa.Column('agents_with_empty_narrative', sa.JSON(), nullable=True),
    sa.Column('human_quality_note', sa.Text(), nullable=True),
    sa.Column('human_quality_rating', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.run_id'], ),
    sa.PrimaryKeyConstraint('summary_id'),
    sa.UniqueConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_quality_summary')
    # ### end Alembic commands ###
