"""baseline: 8 real, live-imported tables

Revision ID: 4fd6994acf5c
Revises: 
Create Date: 2026-09-24 09:36:52.619487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd6994acf5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('stock_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_ticker', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('primary_exchange', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('stock_id')
    )
    op.create_index(op.f('ix_stocks_canonical_ticker'), 'stocks', ['canonical_ticker'], unique=True)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('financial_profile', sa.JSON(), nullable=True),
    sa.Column('context_and_goals', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('analysis_runs',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('stock_id', sa.Uuid(), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('timeline', sa.String(length=20), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('pass1_completed_at', sa.DateTime(), nullable=True),
    sa.Column('pass2_completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('llm_config', sa.JSON(), nullable=False),
    sa.Column('disagreement_score', sa.Integer(), nullable=True),
    sa.Column('disagreement_class', sa.String(length=20), nullable=True),
    sa.Column('error_log', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('ix_analysis_runs_one_active_per_stock', 'analysis_runs', ['stock_id'], unique=True, sqlite_where=sa.text("status NOT IN ('completed', 'failed')"), postgresql_where=sa.text("status NOT IN ('completed', 'failed')"))
    op.create_index(op.f('ix_analysis_runs_stock_id'), 'analysis_runs', ['stock_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_user_id'), 'analysis_runs', ['user_id'], unique=False)
    op.create_table('agent_outputs',
    sa.Column('output_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.String(length=30), nullable=False),
    sa.Column('agent_pass', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recommendation', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('analysis_confidence', sa.String(length=20), nullable=True),
    sa.Column('key_factors', sa.JSON(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('structured_output', sa.JSON(), nullable=True),
    sa.Column('data_sources_used', sa.JSON(), nullable=True),
    sa.Column('input_agent_outputs', sa.JSON(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.run_id'], ),
    sa.PrimaryKeyConstraint('output_id')
    )
    op.create_index(op.f('ix_agent_outputs_agent_name'), 'agent_outputs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_outputs_run_id'), 'agent_outputs', ['run_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('stock_id', sa.Uuid(), nullable=False),
    sa.Column('stock_outlook_direction', sa.String(length=20), nullable=False),
    sa.Column('overall_confidence', sa.Integer(), nullable=False),
    sa.Column('account_recommendation', sa.JSON(), nullable=False),
    sa.Column('position_size_suggestion', sa.String(length=50), nullable=True),
    sa.Column('key_drivers', sa.JSON(), nullable=False),
    sa.Column('key_risks', sa.JSON(), nullable=False),
    sa.Column('synthesis_narrative', sa.Text(), nullable=False),
    sa.Column('dissenting_views', sa.JSON(), nullable=True),
    sa.Column('bull_case_strength', sa.Integer(), nullable=False),
    sa.Column('bear_case_strength', sa.Integer(), nullable=False),
    sa.Column('expected_return_tier', sa.String(length=20), nullable=True),
    sa.Column('expected_return_pct', sa.Float(), nullable=True),
    sa.Column('expected_return_low', sa.Float(), nullable=True),
    sa.Column('expected_return_high', sa.Float(), nullable=True),
    sa.Column('expected_return_basis', sa.Text(), nullable=True),
    sa.Column('return_estimate_confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.run_id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index(op.f('ix_recommendations_stock_id'), 'recommendations', ['stock_id'], unique=False)
    op.create_table('shadow_predictions',
    sa.Column('shadow_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('primary_outlook_direction', sa.String(length=20), nullable=False),
    sa.Column('primary_confidence', sa.Integer(), nullable=False),
    sa.Column('primary_projected_return_tier', sa.String(length=20), nullable=True),
    sa.Column('shadow_outlook_direction', sa.String(length=20), nullable=False),
    sa.Column('shadow_confidence', sa.Integer(), nullable=False),
    sa.Column('shadow_projected_return_tier', sa.String(length=20), nullable=True),
    sa.Column('divergence_magnitude', sa.String(length=10), nullable=False),
    sa.Column('primary_accuracy_at_checkpoint', sa.Float(), nullable=True),
    sa.Column('shadow_accuracy_at_checkpoint', sa.Float(), nullable=True),
    sa.Column('which_was_closer', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.run_id'], ),
    sa.PrimaryKeyConstraint('shadow_id')
    )
    op.create_index(op.f('ix_shadow_predictions_analysis_run_id'), 'shadow_predictions', ['analysis_run_id'], unique=False)
    op.create_table('predictions',
    sa.Column('prediction_id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('stock_id', sa.Uuid(), nullable=False),
    sa.Column('price_at_recommendation', sa.Float(), nullable=False),
    sa.Column('benchmark_price_at_recommendation', sa.Float(), nullable=False),
    sa.Column('predicted_return_tier', sa.String(length=20), nullable=True),
    sa.Column('predicted_return_pct', sa.Float(), nullable=True),
    sa.Column('predicted_return_low', sa.Float(), nullable=True),
    sa.Column('predicted_return_high', sa.Float(), nullable=True),
    sa.Column('predicted_capital_appreciation_pct', sa.Float(), nullable=True),
    sa.Column('predicted_dividend_income_pct', sa.Float(), nullable=True),
    sa.Column('predicted_tax_drag_pct', sa.Float(), nullable=True),
    sa.Column('return_estimate_confidence', sa.Integer(), nullable=True),
    sa.Column('estimated_round_trip_cost_pct', sa.Float(), nullable=True),
    sa.Column('direction_scores', sa.JSON(), nullable=True),
    sa.Column('magnitude_scores', sa.JSON(), nullable=True),
    sa.Column('relative_score', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('per_agent_scores', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.recommendation_id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ),
    sa.PrimaryKeyConstraint('prediction_id'),
    sa.UniqueConstraint('recommendation_id')
    )
    op.create_index(op.f('ix_predictions_stock_id'), 'predictions', ['stock_id'], unique=False)
    op.create_table('prediction_checkpoints',
    sa.Column('checkpoint_id', sa.Uuid(), nullable=False),
    sa.Column('prediction_id', sa.Uuid(), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('actual_price', sa.Float(), nullable=True),
    sa.Column('dividends_per_share', sa.Float(), nullable=True),
    sa.Column('benchmark_price', sa.Float(), nullable=True),
    sa.Column('benchmark_dividends_per_share', sa.Float(), nullable=True),
    sa.Column('actual_total_return_pct', sa.Float(), nullable=True),
    sa.Column('actual_return_net_of_costs_pct', sa.Float(), nullable=True),
    sa.Column('benchmark_total_return_pct', sa.Float(), nullable=True),
    sa.Column('prediction_error_pct', sa.Float(), nullable=True),
    sa.Column('return_in_predicted_range', sa.Boolean(), nullable=True),
    sa.Column('interpolated_expected', sa.Float(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id'], ),
    sa.PrimaryKeyConstraint('checkpoint_id')
    )
    op.create_index(op.f('ix_prediction_checkpoints_due_date'), 'prediction_checkpoints', ['due_date'], unique=False)
    op.create_index(op.f('ix_prediction_checkpoints_prediction_id'), 'prediction_checkpoints', ['prediction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_checkpoints_prediction_id'), table_name='prediction_checkpoints')
    op.drop_index(op.f('ix_prediction_checkpoints_due_date'), table_name='prediction_checkpoints')
    op.drop_table('prediction_checkpoints')
    op.drop_index(op.f('ix_predictions_stock_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_shadow_predictions_analysis_run_id'), table_name='shadow_predictions')
    op.drop_table('shadow_predictions')
    op.drop_index(op.f('ix_recommendations_stock_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_agent_outputs_run_id'), table_name='agent_outputs')
    op.drop_index(op.f('ix_agent_outputs_agent_name'), table_name='agent_outputs')
    op.drop_table('agent_outputs')
    op.drop_index(op.f('ix_analysis_runs_user_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_stock_id'), table_name='analysis_runs')
    op.drop_index('ix_analysis_runs_one_active_per_stock', table_name='analysis_runs', sqlite_where=sa.text("status NOT IN ('completed', 'failed')"), postgresql_where=sa.text("status NOT IN ('completed', 'failed')"))
    op.drop_table('analysis_runs')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_stocks_canonical_ticker'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
