"""add agent_outputs input_field_coverage

Revision ID: 5ef880ea002b
Revises: 7e8008cf8a3b
Create Date: 2026-09-24 16:12:40.294608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef880ea002b'
down_revision: Union[str, None] = '7e8008cf8a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_outputs', sa.Column('input_field_coverage', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_outputs', 'input_field_coverage')
    # ### end Alembic commands ###
