"""add llm_calls table

Revision ID: 7e8008cf8a3b
Revises: a94a09aba2b9
Create Date: 2026-09-24 10:17:46.810617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e8008cf8a3b'
down_revision: Union[str, None] = 'a94a09aba2b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_calls',
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('context_tag', sa.String(length=20), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('call_site', sa.String(length=40), nullable=False),
    sa.Column('agent_pass', sa.String(length=10), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=False),
    sa.Column('template_id', sa.String(length=60), nullable=True),
    sa.Column('template_version', sa.String(length=10), nullable=True),
    sa.Column('prompt_path', sa.String(length=255), nullable=True),
    sa.Column('context_path', sa.String(length=255), nullable=True),
    sa.Column('response_path', sa.String(length=255), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('thinking_chars', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('finish_reason', sa.String(length=20), nullable=True),
    sa.Column('parsed_ok', sa.Boolean(), nullable=True),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('validator_passed', sa.Boolean(), nullable=True),
    sa.Column('validator_errors', sa.JSON(), nullable=True),
    sa.Column('auto_trimmed', sa.Boolean(), nullable=True),
    sa.Column('agent_output_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_output_id'], ['agent_outputs.output_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.run_id'], ),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_index(op.f('ix_llm_calls_call_site'), 'llm_calls', ['call_site'], unique=False)
    op.create_index(op.f('ix_llm_calls_run_id'), 'llm_calls', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_calls_run_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_call_site'), table_name='llm_calls')
    op.drop_table('llm_calls')
    # ### end Alembic commands ###
