"""add analysis_runs context tags

Revision ID: a94a09aba2b9
Revises: 4fd6994acf5c
Create Date: 2026-09-24 09:56:35.347517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94a09aba2b9'
down_revision: Union[str, None] = '4fd6994acf5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_runs', sa.Column('exchange', sa.String(length=20), nullable=True))
    op.add_column('analysis_runs', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('analysis_runs', sa.Column('instrument_type', sa.String(length=20), nullable=True))
    op.add_column('analysis_runs', sa.Column('market_cap_bucket', sa.String(length=20), nullable=True))
    op.add_column('analysis_runs', sa.Column('market_regime', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_runs', 'market_regime')
    op.drop_column('analysis_runs', 'market_cap_bucket')
    op.drop_column('analysis_runs', 'instrument_type')
    op.drop_column('analysis_runs', 'currency')
    op.drop_column('analysis_runs', 'exchange')
    # ### end Alembic commands ###
